# Generated by Django 5.0.6 on 2024-06-18 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
