# Generated by Django 5.0.6 on 2024-06-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userproduct_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='tcm_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
