# Generated by Django 5.0.6 on 2024-06-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userproduct_tcm_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproduct',
            old_name='aproved',
            new_name='approved',
        ),
    ]
