# Generated by Django 5.0.6 on 2024-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
