# Generated by Django 5.0.6 on 2024-06-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_userproduct_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='images',
            field=models.ImageField(upload_to='media/photos/user_products'),
        ),
    ]
