# Generated by Django 5.0.6 on 2024-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_userproduct_images_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='images',
            field=models.ImageField(null=True, upload_to='media/photos/user_products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
