# Generated by Django 5.0.6 on 2024-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product Gallery'},
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
