# Generated by Django 5.0.6 on 2024-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='rejected',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
