# Generated by Django 5.0.6 on 2024-07-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_userproduct_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
