# Generated by Django 5.0.6 on 2024-07-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_userproduct_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='images',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos/user_products')),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.userproduct')),
            ],
        ),
    ]
