# Generated by Django 5.0.6 on 2024-07-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_userproduct_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='user_confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
