branch-defaults:
  main:
    environment: django-barterout1-env
    group_suffix: null
global:
  application_name: django-barterout1-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
