# Generated by Django 5.0.6 on 2024-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document',
            field=models.CharField(help_text='Required. Enter a valid document (CPF, RG, or Passport).', max_length=15, unique=True),
        ),
    ]
