# Generated by Django 5.0.6 on 2024-06-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='TCM_wallet',
            field=models.FloatField(default=0),
        ),
    ]
